# Generated by Django 4.0 on 2021-12-09 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stations',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
