# Generated by Django 4.0 on 2021-12-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_stations_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stations',
            options={'verbose_name_plural': 'Stations'},
        ),
        migrations.RenameField(
            model_name='stations',
            old_name='staion_ID',
            new_name='device_id',
        ),
    ]
