# Generated by Django 4.0 on 2021-12-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_rename_sation_data_station_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_data',
            name='ammonia',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='station_data',
            name='turbidity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
