# Generated by Django 4.0 on 2021-12-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_station_data_ammonia_station_data_turbidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_data',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='station_data',
            name='time',
            field=models.TimeField(auto_now=True, null=True),
        ),
    ]
