# Generated by Django 4.0 on 2021-12-11 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_alter_station_data_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stations',
            name='slug',
        ),
    ]
