# Generated by Django 4.0 on 2021-12-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_remove_stations_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='device_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
