# Generated by Django 4.0 on 2021-12-13 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_alter_stations_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station_data',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.stations'),
        ),
    ]
