# Generated by Django 4.0 on 2021-12-13 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0011_alter_station_data_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station_data',
            old_name='device_id',
            new_name='device',
        ),
    ]
