# Generated by Django 4.0 on 2021-12-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0012_rename_device_id_station_data_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_data',
            name='device_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
