# Generated by Django 4.0 on 2022-01-09 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0015_station_data_latitude_station_data_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station_data',
            old_name='device',
            new_name='device_id',
        ),
    ]
