# Generated by Django 4.0 on 2022-01-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0016_rename_device_station_data_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station_data',
            old_name='device_id',
            new_name='device',
        ),
    ]
