# Generated by Django 4.0 on 2022-01-09 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0017_rename_device_id_station_data_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_data',
            name='station_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
